version: '3'
services:
  web:
    build: .
    container_name: sample-flask
    command: python app.py 
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=camp2016



 # MONGO_URI: mongodb://db:27017/camp2016