apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -o k8s/
#     kompose.version: 1.26.0 (40646f47)
#   labels:
#     io.kompose.service: mongo
#   name: mongo
# spec:
#   ports:
#     - name: "27017"
#       port: 27017
#       targetPort: 27017
#   selector:
#     io.kompose.service: mongo
# status:
#   loadBalancer: {}