apiVersion: v1
kind: ReplicationController 
metadata:
   name: todo-app-csgy-9223-web
spec:
   replicas: 3 
   app: todo-app-csgy-9223-web
   template:
      metadata:
         name: todo-app-csgy-9223-web
      labels:
         app: todo-app-csgy-9223-web
      spec:
         containers:
         - name: todo-app-csgy-9223-web
         image: smk8939/app:1.0.0
         ports:
            - containerPort: 8080
