apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-csgy-9223-web
  labels:
    app: todo-app-csgy-9223-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-csgy-9223-web
  template:
    metadata:
      labels:
        app: todo-app-csgy-9223-web
    spec:
      containers:
      - name: todo-app-csgy-9223-web
        image: smk8939/app:1.0.0
        ports:
        - containerPort: 8080
        env:
        # - name: MONGO_URI
        #   value: "mongodb://mongo-svc:27017/camp2016"
        imagePullPolicy: Always
      restartPolicy: Always



