apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mvertes/alpine-mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /data/db/
              name: todo-app-csgy-9223-web
      restartPolicy: Always
      volumes:
        - name: todo-app-csgy-9223-web
          persistentVolumeClaim:
            claimName: todo-app-csgy-9223-web
status: {}




            