apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: todo-app-csgy-9223-web
  name: todo-app-csgy-9223-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
