global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true