apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskapp
  name: flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
