apiVersion: v1
kind: Service
metadata:
  # Annotations provide additional information about the Service
  # Kompose annotations show the version and command used to generate this resource
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.26.0 (40646f47)
  # Labels are key-value pairs used to identify and organize resources
  labels:
    io.kompose.service: todo-flaskapp
  # The name of the Service
  name: todo-flaskapp
spec:
  # The list of ports exposed by the Service
  ports:
  # Each port has a name, port number, and target port number
    - name: "5000"
      port: 5000
      targetPort: 5000
  # The selector determines which pods the Service routes traffic to
  selector:
    io.kompose.service: todo-flaskapp
status:
  loadBalancer: {}
