version: "3.8"

services:
  # Flask app service
  todo-flaskapp:
    # Use the specified Docker image
    image: smk8939/app-new:${DOCKER_TAG:-latest}
    # Map port 5000 on the host to port 5000 in the container
    ports:
      - 5000:5000
    # Name the container
    container_name: flask-app
    # Set environment variables for the Flask app
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    # Depend on the mongo service
    depends_on:
      - mongo
  # MongoDB service
  mongo:
    # Use the specified Docker image
    image: mvertes/alpine-mongo:latest
    # Mount the flaskapp volume to /data/db in the container
    volumes:
     - flaskapp:/data/db/
    # Map port 27017 on the host to port 27017 in the container
    ports:
      - 27017:27017

volumes:
  # Define the flaskapp volume
  flaskapp:
